### ISSUE TITLE
Only a single type ia supported yet

### ISSUE THREAD

**Issue by jonykalavera** [godatadriven/pydantic-avro#34]
I guess this is a known issue but it is worth tracking it.

```
Traceback (most recent call last):
  File "/home/luis/code/avro-schemas/avro_schemas/cli.py", line 51, in generate_models
    convert_file(avsc_path, output_path)
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 157, in convert_file
    file_content = avsc_to_pydantic(avsc_dict)
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 136, in avsc_to_pydantic
    record_type_to_pydantic(schema)
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 123, in record_type_to_pydantic
    t = get_python_type(field["type"])
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 100, in get_python_type
    record_type_to_pydantic(t)
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 123, in record_type_to_pydantic
    t = get_python_type(field["type"])
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 97, in get_python_type
    sub_type = get_python_type(t.get("items"))
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 71, in get_python_type
    raise NotImplementedError("Only a single type ia supported yet")
NotImplementedError: Only a single type ia supported yet
```

**Comment by ffinfo** [comment]
fixed in #54
