### ISSUE TITLE
NotImplementedError: Type {'name': 'foo', 'type': 'int'} not supported yet,

### ISSUE THREAD

**Issue by jonykalavera** [godatadriven/pydantic-avro#35]
```
Traceback (most recent call last):
  File "/home/luis/code/avro-schemas/avro_schemas/cli.py", line 51, in generate_models
    convert_file(avsc_path, output_path)
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 157, in convert_file
    file_content = avsc_to_pydantic(avsc_dict)
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 136, in avsc_to_pydantic
    record_type_to_pydantic(schema)
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 123, in record_type_to_pydantic
    t = get_python_type(field["type"])
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 100, in get_python_type
    record_type_to_pydantic(t)
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 123, in record_type_to_pydantic
    t = get_python_type(field["type"])
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 97, in get_python_type
    sub_type = get_python_type(t.get("items"))
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 75, in get_python_type
    py_type = get_python_type(c[0])
  File "/home/luis/.cache/pypoetry/virtualenvs/avro-schemas-tmu4cSKQ-py3.6/lib/python3.6/site-packages/pydantic_avro/avro_to_pydantic.py", line 107, in get_python_type
    f"Type {t} not supported yet, "
NotImplementedError: Type {'name': 'product_id', 'type': 'int'} not supported yet, please report this at https://github.com/godatadriven/pydantic-avro/issues
```

**Comment by ffinfo** [comment]
Can you show me the complete avro schema to see in what context this happens?

**Comment by rjurney** [comment]
@ffinfo happens here:

```python
    class Movie(NodeBase):
        """A film node in hollywood."""

        entity_type = "movie"
        genre: str
        title: str
        year: str
        length: typing.Optional[typing.Union[str, int]]
        gross: typing.Optional[int]
        rating: str

        @validator("length")
        def convert_hours_minutes_to_int_minutes(cls, x):
            if x and isinstance(x, str):
                x = text_runtime_to_minutes(x)
            return x
```

Can you please advise how to handle `None`?

**Comment by rjurney** [comment]
Ok, I see that `typing.Optional` is not supported...

**Comment by ffinfo** [comment]
I think multiple things here was not supported yet.
- no support for unions yet (now there is)
- No support for avro int types (now there is)

see also:
https://github.com/godatadriven/pydantic-avro/pull/59
