### ISSUE TITLE
Any not implemented?

### ISSUE THREAD

**Issue by mjhaller** [godatadriven/pydantic-avro#99]
Any thoughts on supporting  `Any`?  Is there another way to express the same concept?  Admittedly, I'm not sure what the avro schema for this idea would look like.  It's essentially any valid json.

```
from pydantic_avro.base import AvroBase
from typing import Any
class Foo(AvroBase):
    bar: Any
print(schema.parse_schema(Foo.avro_schema()))
Traceback (most recent call last):
  File "/Users/mhaller/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/232.8660.197/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 10, in <module>
  File "/Users/mhaller/projects/data/kafka-event-config/.venv/lib/python3.11/site-packages/pydantic_avro/base.py", line 29, in avro_schema
    return cls._avro_schema(schema, namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mhaller/projects/data/kafka-event-config/.venv/lib/python3.11/site-packages/pydantic_avro/base.py", line 185, in _avro_schema
    fields = get_fields(schema)
             ^^^^^^^^^^^^^^^^^^
  File "/Users/mhaller/projects/data/kafka-event-config/.venv/lib/python3.11/site-packages/pydantic_avro/base.py", line 166, in get_fields
    avro_type_dict = get_type(value)
                     ^^^^^^^^^^^^^^^
  File "/Users/mhaller/projects/data/kafka-event-config/.venv/lib/python3.11/site-packages/pydantic_avro/base.py", line 154, in get_type
    raise NotImplementedError(
NotImplementedError: Type 'None' not support yet, please report this at https://github.com/godatadriven/pydantic-avro/issues
```

**Comment by mjhaller** [comment]
I'm going to close this.  I was (am?) new to Avro and you cannot specify arbitrary objects like you can in JSON Schema.  The best you can do is provide a `dict[str, str]`.   Interestingly `dict[str, Any]` works but creates the same schema as `dict[str,str]`.   That perhaps is its own bug, but true `Any` support seems impossible.  If you really want to support objects in your field, you have to just embed them as strings.

Someone feel free to correct me if this seems wrong.

**Comment by mjhaller** [comment]
see https://github.com/bmizhen/rec-avro which is related.   I'm considering reopening this.  I think there is a way to support `Any` but not infinitely nested.   Maybe up to 3-4 levels.  It would be a gnarly mess, but it is possible with unions.
